
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memoir
    ports:
      - '5432:5432'
    user: postgres
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
