
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memoir
    ports:
      - '5432:5432'
    user: postgres
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jixer@jixer.com
      PGADMIN_DEFAULT_PASSWORD: 1234
